swagger: '2.0'
info:
  title: '司法陽光網判決API'
  version: '0.1'
host: 'api.jrf.org.tw'
basePath: '/'
schemes:
  - 'https'
consumes:
  - 'application/json'
produces:
  - 'application/json'
paths:
  /{court_code}/{story_identity}:
    $ref: 'paths/story.yml'
  /{court_code}/{story_identity}/verdict:
    $ref: 'paths/verdict.yml'
  /{court_code}/{story_identity}/rules:
    $ref: 'paths/rules.yml'
  /{court_code}/{story_identity}/schedules:
    $ref: 'paths/schedules.yml'
  /search/stories:
    $ref: 'paths/stories.yml'
definitions:
  Court:
    $ref: 'definitions/court.yml'
  error:
    $ref: 'definitions/error.yml'
  identity:
    $ref: 'definitions/identity.yml'
  pagination_response:
    $ref: 'definitions/pagination_response.yml'
  Rule:
    $ref: 'definitions/rule.yml'
  Schedule:
    $ref: 'definitions/schedule.yml'
  Story:
    $ref: 'definitions/story.yml'
  story_index:
    $ref: 'definitions/story_index.yml'
  story_partial:
    $ref: 'definitions/story_partial.yml'
  story_show:
    $ref: 'definitions/story_show.yml'
  Verdict:
    $ref: 'definitions/verdict.yml'
parameters:
  court_code:
    name: court_code
    in: path
    description: "法院代號 ex: KSB"
    require: true
    type: string
    x-pattern: \w{3}
  story_identity:
    name: story_identity
    in: path
    description: "案件識別碼 {story_type}-{story_year}-{story_word}-{story_number} ex: 行政-104-訴-157"
    require: true
    type: string
    x-pattern: .*-\d{2,3}-.+-\d+
